services:
  api1:
      build: .
      hostname: api1
      command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --threads=2 --workers 1
      networks:
        - db-network
      expose:
        - "8000"
      depends_on:
        - db
        - pgbouncer
      environment:
        - DATABASE_URL=postgres://postgres:1234@pgbouncer:6432/postgres?sslmode=disable
      deploy:
        resources:
          limits:
            cpus: '0.25'
            memory: '0.5GB'
  api2:
      build: .
      hostname: api2
      command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --threads=2 --workers 1
      networks:
        - db-network
      expose:
        - "8000"
      depends_on:
        - db
        - pgbouncer
      environment:
        - DATABASE_URL=postgres://postgres:1234@pgbouncer:6432/postgres?sslmode=disable
      deploy:
        resources:
          limits:
            cpus: '0.25'
            memory: '0.5GB'
  nginx: # Load Balancer
    image: nginx:1.27.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - db-network
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.3GB'
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
  db:
   image: postgres
   command: postgres -c shared_buffers=378MB -c max_connections=100
   networks:
      - db-network
   environment:
      - "POSTGRES_DB=postgres" 
      - "POSTGRES_USER=postgres" 
      - "POSTGRES_PASSWORD=1234" 
   deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.5GB'
  pgbouncer:
    image: edoburu/pgbouncer:v1.23.1-p1
    depends_on:
      - db
    ports:
      - 5432:6432
    networks:
      - db-network
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt
    environment:
      - DATABASE_URL=postgres://postgres:1234@db:5432/postgres
      - POOL_MODE=transaction  
      - MAX_DB_CONNECTIONS=100  
      - DEFAULT_POOL_SIZE=40  
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.2GB'
networks:
  db-network:
    driver: bridge
volumes:
  postgres_data: