services:
  api1:
      build: .
      hostname: api1
      command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3
      expose:
        - "8000"
      depends_on:
        - db
      environment:
        - DATABASE_URL=postgres://postgres:1234@db:5432/postgres
      deploy:
        resources:
          limits:
            cpus: '0.25'
            memory: '0.5GB'
  api2:
      build: .
      hostname: api2
      command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3
      expose:
        - "8000"
      depends_on:
        - db
      environment:
        - DATABASE_URL=postgres://postgres:1234@db:5432/postgres
      deploy:
        resources:
          limits:
            cpus: '0.25'
            memory: '0.5GB'
  nginx: # Load Balancer
    image: nginx:1.27.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  db:
   image: postgres
   ports:
      - "5432:5432"
   environment:
      - "POSTGRES_DB=postgres" 
      - "POSTGRES_USER=postgres" 
      - "POSTGRES_PASSWORD=1234" 
   deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
volumes:
  postgres_data: