services:
  api1:
      build: .
      hostname: api1
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./:/app
      expose:
        - "8000"
      depends_on:
        - db
      environment:
        - DATABASE_URL=postgres://postgres:1234@db:5432/postgres
  api2:
      build: .
      hostname: api2
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./:/app
      expose:
        - "8000"
      depends_on:
        - db
      environment:
        - DATABASE_URL=postgres://postgres:1234@db:5432/postgres

  nginx: # Load Balancer
    image: nginx:1.27.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "80:80"
  db:
   image: postgres
   ports:
      - "5432:5432"
   environment:
      - "POSTGRES_DB=postgres" 
      - "POSTGRES_USER=postgres" 
      - "POSTGRES_PASSWORD=1234" 
volumes:
  postgres_data: