# Generated by Django 5.1.2 on 2024-10-10 02:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_alter_pessoa_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='stack',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), null=True, size=None),
        ),
    ]
